@startuml Notification

actor User

database "Notifications DB" as notifications_db 
database "History DB" as history_db
database "Periodicity DB" as periodicity_db

control "API" as api 
queue "Notification Queue" as notification_queue
control "Worker" as worker 
control "Generator" as generator
control "Admin" as admin 

User --> api
api --> notifications_db
api --> notification_queue
notification_queue --> worker
worker --> history_db
worker --> notifications_db

api --> periodicity_db
generator --> periodicity_db
generator --> notifications_db
generator --> notification_queue

admin --> notifications_db
admin --> notification_queue
admin --> history_db
admin --> periodicity_db

@enduml
